# Generated by Django 4.2.7 on 2026-01-19 12:00
# P0.8: Initial migration for System model with all fields including new P0.8 fields

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Basic Info
                ('system_code', models.CharField(max_length=100, unique=True, verbose_name='System Code')),
                ('system_name', models.CharField(max_length=255, verbose_name='System Name')),
                ('system_name_en', models.CharField(blank=True, max_length=255, verbose_name='System Name (English)')),
                ('purpose', models.TextField(blank=True, verbose_name='Purpose')),
                ('scope', models.CharField(blank=True, choices=[('internal_unit', 'Nội bộ đơn vị'), ('org_wide', 'Toàn bộ'), ('external', 'Bên ngoài')], max_length=50, verbose_name='Scope')),
                ('target_users', models.JSONField(blank=True, default=list, help_text='["leader", "staff", "business", "citizen"]')),

                # SECTION 2: Business Context (P0.8 - NEW FIELDS)
                ('business_objectives', models.JSONField(blank=True, default=list, help_text='List of business objectives (max 5 items recommended)')),
                ('business_processes', models.JSONField(blank=True, default=list, help_text='List of main business processes supported by the system')),
                ('has_design_documents', models.BooleanField(default=False, help_text='Có đủ hồ sơ phân tích thiết kế hệ thống?', verbose_name='Has Design Documents?')),
                ('user_types', models.JSONField(blank=True, default=list, help_text='User types: internal_leadership, internal_staff, internal_reviewer, external_business, external_citizen, external_local, external_agency')),
                ('annual_users', models.IntegerField(blank=True, help_text='Số lượng người dùng hàng năm', null=True, verbose_name='Annual Users Count')),

                # SECTION 3: Technology Architecture (P0.8 - NEW FIELDS)
                ('programming_language', models.CharField(blank=True, help_text='e.g., Python, Java, JavaScript, C#', max_length=255, verbose_name='Programming Language')),
                ('framework', models.CharField(blank=True, help_text='e.g., Django, Spring Boot, React, Angular', max_length=255, verbose_name='Framework/Library')),
                ('database_name', models.CharField(blank=True, help_text='e.g., PostgreSQL, MySQL, MongoDB, Oracle', max_length=255, verbose_name='Database')),
                ('hosting_platform', models.CharField(blank=True, choices=[('cloud', 'Cloud'), ('on_premise', 'On-premise'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Hosting Platform')),

                # SECTION 4: Data Architecture (P0.8 - NEW FIELDS)
                ('data_sources', models.JSONField(blank=True, default=list, help_text='List of data sources (databases, APIs, files, etc.)')),
                ('data_classification_type', models.CharField(blank=True, help_text='e.g., Public, Internal, Confidential, Secret', max_length=255, verbose_name='Data Classification')),
                ('data_volume', models.CharField(blank=True, help_text='e.g., 100GB, 1TB, 10TB', max_length=255, verbose_name='Data Volume')),

                # SECTION 5: System Integration (P0.8 - NEW FIELDS)
                ('integrated_internal_systems', models.JSONField(blank=True, default=list, help_text='List of integrated internal systems')),
                ('integrated_external_systems', models.JSONField(blank=True, default=list, help_text='List of integrated external systems')),
                ('api_list', models.JSONField(blank=True, default=list, help_text='List of APIs/Webservices provided or consumed')),
                ('data_exchange_method', models.CharField(blank=True, help_text='e.g., REST API, SOAP, File Transfer, Database Sync', max_length=255, verbose_name='Data Exchange Method')),

                # SECTION 6: Security (P0.8 - NEW FIELDS)
                ('authentication_method', models.CharField(blank=True, choices=[('username_password', 'Username/Password'), ('sso', 'SSO'), ('ldap', 'LDAP'), ('oauth', 'OAuth'), ('saml', 'SAML'), ('biometric', 'Biometric'), ('other', 'Khác')], max_length=100, verbose_name='Authentication Method')),
                ('has_encryption', models.BooleanField(default=False, help_text='Mã hóa dữ liệu', verbose_name='Has Data Encryption?')),
                ('has_audit_log', models.BooleanField(default=False, help_text='Có log audit trail?', verbose_name='Has Audit Log?')),
                ('compliance_standards_list', models.CharField(blank=True, help_text='e.g., ISO 27001, GDPR, PCI DSS, SOC 2', max_length=500, verbose_name='Compliance Standards')),

                # SECTION 7: Infrastructure (P0.8 - NEW FIELDS)
                ('server_configuration', models.CharField(blank=True, help_text='CPU, RAM, Storage specifications', max_length=500, verbose_name='Server Configuration')),
                ('storage_capacity', models.CharField(blank=True, help_text='Total storage allocated for the system', max_length=255, verbose_name='Storage Capacity')),
                ('backup_plan', models.CharField(blank=True, help_text='Backup frequency, retention, and strategy', max_length=500, verbose_name='Backup Plan')),
                ('disaster_recovery_plan', models.CharField(blank=True, help_text='DR strategy, RTO, RPO', max_length=500, verbose_name='Disaster Recovery Plan')),

                # System Group & Status
                ('system_group', models.CharField(blank=True, choices=[('platform', 'Nền tảng'), ('business', 'Nghiệp vụ'), ('portal', 'Cổng thông tin'), ('website', 'Website'), ('bi', 'BI/Báo cáo'), ('esb', 'ESB/Tích hợp'), ('other', 'Khác')], max_length=50, verbose_name='System Group')),
                ('status', models.CharField(choices=[('operating', 'Đang vận hành'), ('pilot', 'Thí điểm'), ('stopped', 'Dừng'), ('replacing', 'Sắp thay thế')], default='operating', max_length=20, verbose_name='Status')),
                ('go_live_date', models.DateField(blank=True, null=True, verbose_name='Go Live Date')),
                ('current_version', models.CharField(blank=True, max_length=50, verbose_name='Current Version')),
                ('upgrade_history', models.JSONField(blank=True, default=list)),

                # Business & Technical Owners
                ('business_owner', models.CharField(blank=True, max_length=255, verbose_name='Business Owner')),
                ('technical_owner', models.CharField(blank=True, max_length=255, verbose_name='Technical Owner')),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('responsible_phone', models.CharField(blank=True, max_length=20)),
                ('responsible_email', models.EmailField(blank=True)),

                # User Statistics
                ('users_total', models.IntegerField(blank=True, null=True, verbose_name='Total Users')),
                ('users_mau', models.IntegerField(blank=True, null=True, verbose_name='MAU')),
                ('users_dau', models.IntegerField(blank=True, null=True, verbose_name='DAU')),
                ('num_organizations', models.IntegerField(blank=True, null=True, verbose_name='Number of Organizations')),

                # Criticality (P0.8: Removed 'critical' option)
                ('criticality_level', models.CharField(choices=[('high', 'Quan trọng'), ('medium', 'Trung bình'), ('low', 'Thấp')], default='medium', max_length=20, verbose_name='Criticality Level')),

                # Form Level
                ('form_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], default=1, verbose_name='Form Level')),

                # Timestamps
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),

                # Foreign Keys
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'db_table': 'systems',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['org', 'status'], name='systems_org_status_idx'),
                    models.Index(fields=['system_code'], name='systems_code_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='system',
            constraint=models.UniqueConstraint(fields=('org', 'system_code'), name='systems_org_code_unique'),
        ),
    ]
