# Generated by Django 4.2.7 on 2026-01-19 13:00
# P0.8: Add 24 new fields to System model

from django.db import migrations, models


def migrate_criticality_level(apps, schema_editor):
    """
    Migrate 'critical' (Cực kỳ quan trọng) → 'high' (Quan trọng)
    Per customer request: "Bỏ Cực kỳ quan trọng"
    """
    System = apps.get_model('systems', 'System')
    updated_count = System.objects.filter(criticality_level='critical').update(criticality_level='high')
    if updated_count > 0:
        print(f"Migrated {updated_count} systems from 'critical' to 'high' criticality level")


def reverse_criticality_level(apps, schema_editor):
    """Reverse migration - no action (can't restore original values)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        # SECTION 2: Business Context (5 new fields)
        migrations.AddField(
            model_name='system',
            name='business_objectives',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of business objectives (max 5 items recommended)'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='business_processes',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of main business processes supported by the system'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='has_design_documents',
            field=models.BooleanField(
                default=False,
                verbose_name='Has Design Documents?',
                help_text='Có đủ hồ sơ phân tích thiết kế hệ thống?'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='user_types',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='User types: internal_leadership, internal_staff, internal_reviewer, external_business, external_citizen, external_local, external_agency'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='annual_users',
            field=models.IntegerField(
                null=True,
                blank=True,
                verbose_name='Annual Users Count',
                help_text='Số lượng người dùng hàng năm'
            ),
        ),

        # SECTION 3: Technology Architecture (4 new fields)
        migrations.AddField(
            model_name='system',
            name='programming_language',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
                verbose_name='Programming Language',
                help_text='e.g., Python, Java, JavaScript, C#'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='framework',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
                verbose_name='Framework/Library',
                help_text='e.g., Django, Spring Boot, React, Angular'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='database_name',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
                verbose_name='Database',
                help_text='e.g., PostgreSQL, MySQL, MongoDB, Oracle'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='hosting_platform',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('cloud', 'Cloud'),
                    ('on_premise', 'On-premise'),
                    ('hybrid', 'Hybrid'),
                ],
                blank=True,
                default='',
                verbose_name='Hosting Platform'
            ),
        ),

        # SECTION 4: Data Architecture (3 new fields)
        migrations.AddField(
            model_name='system',
            name='data_sources',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of data sources (databases, APIs, files, etc.)'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='data_classification_type',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
                verbose_name='Data Classification',
                help_text='e.g., Public, Internal, Confidential, Secret'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='data_volume',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
                verbose_name='Data Volume',
                help_text='e.g., 100GB, 1TB, 10TB'
            ),
        ),

        # SECTION 5: System Integration (4 new fields)
        migrations.AddField(
            model_name='system',
            name='integrated_internal_systems',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of integrated internal systems'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='integrated_external_systems',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of integrated external systems'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='api_list',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of APIs/Webservices provided or consumed'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='data_exchange_method',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
                verbose_name='Data Exchange Method',
                help_text='e.g., REST API, SOAP, File Transfer, Database Sync'
            ),
        ),

        # SECTION 6: Security (4 new fields)
        migrations.AddField(
            model_name='system',
            name='authentication_method',
            field=models.CharField(
                max_length=100,
                choices=[
                    ('username_password', 'Username/Password'),
                    ('sso', 'SSO'),
                    ('ldap', 'LDAP'),
                    ('oauth', 'OAuth'),
                    ('saml', 'SAML'),
                    ('biometric', 'Biometric'),
                    ('other', 'Khác'),
                ],
                blank=True,
                default='',
                verbose_name='Authentication Method'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='has_encryption',
            field=models.BooleanField(
                default=False,
                verbose_name='Has Data Encryption?',
                help_text='Mã hóa dữ liệu'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='has_audit_log',
            field=models.BooleanField(
                default=False,
                verbose_name='Has Audit Log?',
                help_text='Có log audit trail?'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='compliance_standards_list',
            field=models.CharField(
                max_length=500,
                blank=True,
                default='',
                verbose_name='Compliance Standards',
                help_text='e.g., ISO 27001, GDPR, PCI DSS, SOC 2'
            ),
        ),

        # SECTION 7: Infrastructure (4 new fields)
        migrations.AddField(
            model_name='system',
            name='server_configuration',
            field=models.CharField(
                max_length=500,
                blank=True,
                default='',
                verbose_name='Server Configuration',
                help_text='CPU, RAM, Storage specifications'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='storage_capacity',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
                verbose_name='Storage Capacity',
                help_text='Total storage allocated for the system'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='backup_plan',
            field=models.CharField(
                max_length=500,
                blank=True,
                default='',
                verbose_name='Backup Plan',
                help_text='Backup frequency, retention, and strategy'
            ),
        ),
        migrations.AddField(
            model_name='system',
            name='disaster_recovery_plan',
            field=models.CharField(
                max_length=500,
                blank=True,
                default='',
                verbose_name='Disaster Recovery Plan',
                help_text='DR strategy, RTO, RPO'
            ),
        ),

        # Update criticality_level choices (remove 'critical' option)
        migrations.AlterField(
            model_name='system',
            name='criticality_level',
            field=models.CharField(
                max_length=20,
                choices=[
                    # Removed ('critical', 'Tối quan trọng') per customer request P0.8
                    ('high', 'Quan trọng'),
                    ('medium', 'Trung bình'),
                    ('low', 'Thấp'),
                ],
                default='medium',
                verbose_name='Criticality Level'
            ),
        ),

        # Data migration: migrate 'critical' to 'high'
        migrations.RunPython(migrate_criticality_level, reverse_criticality_level),
    ]
