# Generated by Claude Code 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_p08_phase1_all_changes'),
    ]

    operations = [
        # SystemArchitecture: Update ARCHITECTURE_TYPE_CHOICES (add SOA, Serverless, SaaS)
        migrations.AlterField(
            model_name='systemarchitecture',
            name='architecture_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('monolithic', 'Monolithic'),
                    ('modular', 'Modular'),
                    ('microservices', 'Microservices'),
                    ('soa', 'SOA'),
                    ('serverless', 'Serverless'),
                    ('saas', 'SaaS'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='Architecture Type'
            ),
        ),
        # SystemArchitecture: Add new P1 fields
        migrations.AddField(
            model_name='systemarchitecture',
            name='is_multi_tenant',
            field=models.BooleanField(default=False, verbose_name='Multi-tenant Architecture'),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='has_layered_architecture',
            field=models.BooleanField(default=False, verbose_name='Has Layered Architecture (4-tier)'),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='layered_architecture_details',
            field=models.TextField(blank=True, help_text='Presentation, Business Logic, Data Access, Integration'),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='containerization',
            field=models.CharField(
                blank=True,
                choices=[
                    ('docker', 'Docker'),
                    ('kubernetes', 'Kubernetes'),
                    ('openshift', 'OpenShift'),
                    ('none', 'Không sử dụng'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='Containerization'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='api_style',
            field=models.CharField(
                blank=True,
                choices=[
                    ('rest', 'REST API'),
                    ('graphql', 'GraphQL'),
                    ('grpc', 'gRPC'),
                    ('soap', 'SOAP'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='API Style'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='messaging_queue',
            field=models.CharField(
                blank=True,
                choices=[
                    ('kafka', 'Apache Kafka'),
                    ('rabbitmq', 'RabbitMQ'),
                    ('activemq', 'ActiveMQ'),
                    ('redis_pubsub', 'Redis Pub/Sub'),
                    ('none', 'Không sử dụng'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='Messaging/Queue System'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='cache_system',
            field=models.CharField(
                blank=True,
                choices=[
                    ('redis', 'Redis'),
                    ('memcached', 'Memcached'),
                    ('none', 'Không sử dụng'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='Cache System'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='search_engine',
            field=models.CharField(
                blank=True,
                choices=[
                    ('elasticsearch', 'Elasticsearch'),
                    ('solr', 'Apache Solr'),
                    ('none', 'Không sử dụng'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='Search Engine'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='reporting_bi_tool',
            field=models.CharField(
                blank=True,
                choices=[
                    ('powerbi', 'Microsoft Power BI'),
                    ('tableau', 'Tableau'),
                    ('metabase', 'Metabase'),
                    ('superset', 'Apache Superset'),
                    ('custom', 'Tự phát triển'),
                    ('none', 'Không có'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='Reporting/BI Tool'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='source_repository',
            field=models.CharField(
                blank=True,
                choices=[
                    ('gitlab', 'GitLab'),
                    ('github', 'GitHub'),
                    ('bitbucket', 'Bitbucket'),
                    ('azure_devops', 'Azure DevOps'),
                    ('on_premise', 'On-premise Git'),
                    ('none', 'Không quản lý'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='Source Code Repository'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='has_cicd',
            field=models.BooleanField(default=False, verbose_name='Has CI/CD Pipeline'),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='cicd_tool',
            field=models.CharField(
                blank=True,
                choices=[
                    ('jenkins', 'Jenkins'),
                    ('gitlab_ci', 'GitLab CI/CD'),
                    ('github_actions', 'GitHub Actions'),
                    ('azure_pipelines', 'Azure Pipelines'),
                    ('circle_ci', 'CircleCI'),
                    ('travis_ci', 'Travis CI'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='CI/CD Tool'
            ),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='has_automated_testing',
            field=models.BooleanField(default=False, verbose_name='Has Automated Testing'),
        ),
        migrations.AddField(
            model_name='systemarchitecture',
            name='automated_testing_tools',
            field=models.CharField(blank=True, help_text='e.g., Jest, Pytest, Selenium, JUnit', max_length=255),
        ),
        # SystemDataInfo: Add new P1 fields
        migrations.AddField(
            model_name='systemdatainfo',
            name='secondary_databases',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of secondary/other databases used, e.g., ["Redis", "MongoDB"]'
            ),
        ),
        migrations.AddField(
            model_name='systemdatainfo',
            name='file_storage_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('file_server', 'File Server'),
                    ('object_storage', 'Object Storage (S3, MinIO)'),
                    ('nas', 'NAS'),
                    ('database_blob', 'Database BLOB'),
                    ('none', 'Không lưu file'),
                    ('other', 'Khác')
                ],
                max_length=50,
                verbose_name='File Storage Type'
            ),
        ),
        migrations.AddField(
            model_name='systemdatainfo',
            name='record_count',
            field=models.BigIntegerField(
                blank=True,
                help_text='Tổng số bản ghi trong CSDL chính',
                null=True,
                verbose_name='Number of Records'
            ),
        ),
        migrations.AddField(
            model_name='systemdatainfo',
            name='data_retention_policy',
            field=models.TextField(
                blank=True,
                help_text='Chính sách lưu trữ dữ liệu (thời gian, quy tắc xóa, archiving)',
                verbose_name='Data Retention Policy'
            ),
        ),
    ]
