# Generated by Django 5.0.1 on 2026-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_attachment_systemarchitecture_systemassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='has_security_documents',
            field=models.BooleanField(default=False, help_text='Có tài liệu ATTT (chính sách, quy trình, hướng dẫn)?', verbose_name='Has Security Documents'),
        ),
        migrations.AddField(
            model_name='system',
            name='security_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Cấp 1'), (2, 'Cấp 2'), (3, 'Cấp 3'), (4, 'Cấp 4'), (5, 'Cấp 5')], help_text='Mức độ an toàn thông tin (1-5)', null=True, verbose_name='Security Level'),
        ),
        migrations.AddField(
            model_name='systemintegration',
            name='api_consumed_count',
            field=models.IntegerField(blank=True, help_text='Số lượng API mà hệ thống gọi từ hệ thống khác', null=True, verbose_name='Number of APIs Consumed'),
        ),
        migrations.AddField(
            model_name='systemintegration',
            name='api_gateway_name',
            field=models.CharField(blank=True, help_text='Kong, AWS API Gateway, Azure API Management, etc.', max_length=100, verbose_name='API Gateway Name'),
        ),
        migrations.AddField(
            model_name='systemintegration',
            name='api_provided_count',
            field=models.IntegerField(blank=True, help_text='Số lượng API mà hệ thống cung cấp cho hệ thống khác', null=True, verbose_name='Number of APIs Provided'),
        ),
        migrations.AddField(
            model_name='systemintegration',
            name='has_api_gateway',
            field=models.BooleanField(default=False, verbose_name='Has API Gateway'),
        ),
        migrations.AddField(
            model_name='systemintegration',
            name='has_api_versioning',
            field=models.BooleanField(default=False, verbose_name='Has API Versioning'),
        ),
        migrations.AddField(
            model_name='systemintegration',
            name='has_rate_limiting',
            field=models.BooleanField(default=False, verbose_name='Has Rate Limiting/Throttling'),
        ),
        migrations.AddField(
            model_name='systemoperations',
            name='compute_specifications',
            field=models.TextField(blank=True, help_text='CPU, RAM, Storage specifications', verbose_name='Compute Specifications'),
        ),
        migrations.AddField(
            model_name='systemoperations',
            name='deployment_location',
            field=models.CharField(blank=True, choices=[('datacenter', 'Data Center'), ('cloud', 'Cloud'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Deployment Location'),
        ),
    ]
