# Generated by Django 5.0.1 on 2026-01-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_system_has_security_documents_system_security_level_and_more'),
        ('systems', '0008_add_p08_phase4_technical_debt'),
    ]

    operations = [
    ]
