# Generated by Django 5.0.1 on 2026-01-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_remove_systemarchitecture_api_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='authentication_method',
            field=models.CharField(blank=True, choices=[('username_password', 'Username/Password'), ('sso', 'SSO'), ('ldap', 'LDAP'), ('oauth', 'OAuth'), ('saml', 'SAML'), ('biometric', 'Biometric'), ('smartcard', 'Smart Card'), ('other', 'Khác')], max_length=100, verbose_name='Authentication Method'),
        ),
    ]
