# Generated by Django 5.0.1 on 2026-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_alter_system_authentication_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='authentication_method',
            field=models.CharField(blank=True, help_text='Authentication methods (can include: username_password, sso, ldap, oauth, saml, biometric, smartcard, or custom values)', max_length=500, verbose_name='Authentication Method'),
        ),
    ]
