# Generated by Django 5.0.1 on 2026-01-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_alter_system_authentication_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='data_classification_type',
            field=models.CharField(blank=True, help_text='Data classification levels (can include: Public, Internal, Confidential, Secret, or custom values)', max_length=500, verbose_name='Data Classification'),
        ),
    ]
