# Generated by Django 5.0.1 on 2026-02-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0027_remove_systemdatainfo_data_retention_policy_and_more'),
        ('systems', '0028_add_custom_policy'),
    ]

    operations = [
    ]
