#!/bin/bash
# Quick API Testing Commands
# Run these on UAT server or from browser console

echo "=== AI Feedback & Policy Management - API Testing ==="
echo ""

# Base URLs
UAT_URL="https://thong-ke-he-thong-uat.mindmaid.ai"
PROD_URL="https://hientrangcds.mst.gov.vn"

# Use UAT for testing
BASE_URL="$UAT_URL"

echo "Base URL: $BASE_URL"
echo ""
echo "Step 1: Login to get JWT token"
echo "================================"
echo ""
echo "Open browser console (F12) on $BASE_URL and run:"
echo ""
echo "// Get token from localStorage or sessionStorage"
echo "const token = localStorage.getItem('access_token') || sessionStorage.getItem('access_token');"
echo "console.log('Token:', token);"
echo ""
echo "Or use curl on UAT server:"
echo ""
echo "curl -X POST '$BASE_URL/api/accounts/login/' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"username\": \"admin\", \"password\": \"Admin@2026\"}'"
echo ""
echo "---"
echo ""

echo "Step 2: Test APIs (Replace TOKEN with actual token)"
echo "===================================================="
echo ""

echo "# Test 1: Get Active Policies (Public API)"
echo "curl -X GET '$BASE_URL/api/ai-feedback/active_policies/' \\"
echo "  -H 'Authorization: Bearer TOKEN'"
echo ""

echo "# Test 2: Get Policy Status (Admin Only)"
echo "curl -X GET '$BASE_URL/api/ai-feedback/policy_status/' \\"
echo "  -H 'Authorization: Bearer TOKEN'"
echo ""

echo "# Test 3: List Custom Policies (Admin Only)"
echo "curl -X GET '$BASE_URL/api/custom-policies/' \\"
echo "  -H 'Authorization: Bearer TOKEN'"
echo ""

echo "# Test 4: Create Custom Policy (Admin Only)"
echo "curl -X POST '$BASE_URL/api/custom-policies/' \\"
echo "  -H 'Authorization: Bearer TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"category\": \"accuracy\","
echo "    \"rule\": \"Always verify SQL results before generating answer\","
echo "    \"priority\": \"high\","
echo "    \"rationale\": \"Users reported incorrect data multiple times\""
echo "  }'"
echo ""

echo "# Test 5: Regenerate Policies (Admin Only)"
echo "curl -X POST '$BASE_URL/api/ai-feedback/regenerate_policies/' \\"
echo "  -H 'Authorization: Bearer TOKEN'"
echo ""

echo "# Test 6: Update Custom Policy (Admin Only, replace {id})"
echo "curl -X PATCH '$BASE_URL/api/custom-policies/1/' \\"
echo "  -H 'Authorization: Bearer TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"priority\": \"medium\"}'"
echo ""

echo "# Test 7: Delete Custom Policy (Admin Only, replace {id})"
echo "curl -X DELETE '$BASE_URL/api/custom-policies/1/' \\"
echo "  -H 'Authorization: Bearer TOKEN'"
echo ""

echo ""
echo "=== Browser Console Testing (Easier) ==="
echo "========================================"
echo ""
echo "Open browser console on $BASE_URL and run:"
echo ""
echo "// Get token"
echo "const token = localStorage.getItem('access_token') || sessionStorage.getItem('access_token');"
echo ""
echo "// Test 1: Active Policies"
echo "fetch('/api/ai-feedback/active_policies/', {"
echo "  headers: { 'Authorization': 'Bearer ' + token }"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "// Test 2: Policy Status"
echo "fetch('/api/ai-feedback/policy_status/', {"
echo "  headers: { 'Authorization': 'Bearer ' + token }"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "// Test 3: List Custom Policies"
echo "fetch('/api/custom-policies/', {"
echo "  headers: { 'Authorization': 'Bearer ' + token }"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "// Test 4: Create Custom Policy"
echo "fetch('/api/custom-policies/', {"
echo "  method: 'POST',"
echo "  headers: {"
echo "    'Authorization': 'Bearer ' + token,"
echo "    'Content-Type': 'application/json'"
echo "  },"
echo "  body: JSON.stringify({"
echo "    category: 'accuracy',"
echo "    rule: 'Always verify SQL results',"
echo "    priority: 'high',"
echo "    rationale: 'Users reported incorrect data'"
echo "  })"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "// Test 5: Regenerate Policies"
echo "fetch('/api/ai-feedback/regenerate_policies/', {"
echo "  method: 'POST',"
echo "  headers: { 'Authorization': 'Bearer ' + token }"
echo "}).then(r => r.json()).then(console.log)"
echo ""

echo ""
echo "=== Expected Results ==="
echo "======================="
echo ""
echo "✅ All endpoints should return 200/201 status"
echo "✅ Active policies shows merged auto + custom"
echo "✅ Policy status shows injection points"
echo "✅ Create/Update/Delete custom policies work"
echo "✅ Regenerate creates policies from feedback"
echo ""
echo "❌ If 401 Unauthorized: Token expired, login again"
echo "❌ If 403 Forbidden: User not admin/lanhdaobo"
echo "❌ If 404 Not Found on custom-policies: No policies yet (normal)"
echo "❌ If 500 Server Error: Check backend logs"
echo ""
echo "=== Done! Report results back ==="
