# Generated by Django 4.2.7 on 2026-01-19 12:00
# Initial migration for Organization model

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên đơn vị')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã đơn vị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Người liên hệ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn vị',
                'verbose_name_plural': 'Đơn vị',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
